#!/bin/bash
set -euo pipefail

# PARAMÈTRES
SOURCE_DIR="/stockageVM/"
DEST_USER="melveen"
DEST_HOST="192.168.1.31"
DEST_BASE_DIR="/home/melveen/vmsave"

# Génération de la date et heure actuelle
DATE=$(date +"%Y-%m-%d_%H-%M")
DEST_DIR="$DEST_BASE_DIR/stockageVM_$DATE"

# TRANSFERT
echo "Transfert de $SOURCE_DIR vers $DEST_DIR sur $DEST_HOST..."
rsync -aHAXv "$SOURCE_DIR" "$DEST_USER@$DEST_HOST:$DEST_DIR"

echo "Transfert terminé à : $DEST_DIR"
